WarlordsGameBundle_homepage:
    pattern:  /
    defaults: { _controller: WarlordsGameBundle:Main:index }
    requirements:
        _method:  GET
        
        
WarloadsGameBundle_profile:
    pattern: /profile
    defaults: { _controller: WarlordsGameBundle:Page:profile }
    requirements:
        _method: GET
