WarlordsGameBundle_homepage:
    pattern:  /
    defaults: { _controller: WarlordsGameBundle:Main:index }
    requirements:
        _method:  GET
               
WarlordsGameBundle_player:
    pattern: /playerSearch
    defaults: { _controller: WarlordsGameBundle:Page:player }
    requirements:
        _method: GET|POST
  
WarlordsGameBundle_player_attack:
    pattern: /playerSearch/attack/{target_id}
    defaults: { _controller: WarlordsGameBundle:Player:attack }
    requirements:
        _method: GET|POST
        target_id: \d+
        
WarlordsGameBundle_player_add_ally:
    pattern: /playerSearch/ally/{target_id}
    defaults: { _controller: WarlordsGameBundle:Player:ally }
    requirements:
        _method: GET|POST
        target_id: \d+
        
        
WarlordsGameBundle_about:
    pattern:  /about
    defaults: { _controller: WarlordsGameBundle:Page:about }
    requirements:
        _method:  GET

WarlordsGameBundle_guide:
    pattern:  /guide
    defaults: { _controller: WarlordsGameBundle:Page:guide }
    requirements:
        _method:  GET

WarlordsGameBundle_wealth:
    pattern:  /rank/wealth
    defaults: { _controller: WarlordsGameBundle:Page:wealth }
    requirements:
        _method:  GET

WarlordsGameBundle_fame:
    pattern:  /rank/fame
    defaults: { _controller: WarlordsGameBundle:Page:fame }
    requirements:
        _method:  GET

WarlordsGameBundle_profile_get:
    pattern: /profile/{target_id}
    defaults:  { _controller: WarlordsGameBundle:Profile:profile_get }
    requirements:
        _method:  GET
        target_id: \d+

WarlordsGameBundle_profile:
    pattern: /profile
    defaults:  { _controller: WarlordsGameBundle:Profile:profile }
    requirements:
        _method:  GET

WarlordsGameBundle_events:
    pattern: /events/{quantity}
    defaults:  { _controller: WarlordsGameBundle:Page:events }
        
WarlordsGameBundle_ally_list:
    pattern:  /profile/allyList
    defaults: { _controller: WarlordsGameBundle:Profile:allyList }
    requirements:
        _method:  GET
        
WarlordsGameBundle_ally_confirm:
    pattern:  /profile/allyList/confirm/{target_id}
    defaults: { _controller: WarlordsGameBundle:Profile:allyConfirm }
    requirements:
        _method:  GET
        target_id: \d+
                
WarlordsGameBundle_attack:
    pattern: /attack/{target_id}
    defaults:  { _controller: WarlordsGameBundle:Profile:attack }
    requirements:
        _method:  GET
        target_id: \d+
        
WarlordsGameBundle_buy:
    pattern: /profile/buy
    defaults:  { _controller: WarlordsGameBundle:Profile:buy }
    requirements:
        _method: POST
        
WarlordsGameBundle_send_soldiers:
    pattern: /profile/sendSoldiers/{target_id}
    defaults:  { _controller: WarlordsGameBundle:Profile:sendSoldiers }
    requirements:
        _method: GET|POST
        target_id: \d+

WarlordsGameBundle_CheckUnique:
    pattern: /registration/checkunique
    defaults:  { _controller: WarlordsGameBundle:Registration:checkUnique }
    requirements:
        _method: POST

WarlordsGameBundle_RequestResendConfirmation:
    pattern: /resend/request
    defaults:  { _controller: WarlordsGameBundle:ResendConfirmation:request }
    requirements:
        _method: GET

WarlordsGameBundle_ResendConfirmation:
    pattern: /resend/send-email
    defaults:  { _controller: WarlordsGameBundle:ResendConfirmation:sendEmail }
    requirements:
        _method: POST

WarlordsGameBundle_CheckEmail:
    pattern: /resend/check-email
    defaults:  { _controller: WarlordsGameBundle:ResendConfirmation:checkEmail }
    requirements:
        _method: GET

WarlordsGameBundle_contact:
    pattern:  /contact
    defaults: { _controller: WarlordsGameBundle:Contact:contact }
    requirements:
        _method:  GET|POST

genemu_base64:
    resource: "@GenemuFormBundle/Resources/config/routing/base64.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messaging
