<?php

namespace Warlords\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatsRepository extends EntityRepository
{

	// $limit set to 3 to see if the result show correctly; subject to change
	public function getPlayerWithLevel($level, $limit = 4)
	{
		$qb = $this->createQueryBuilder('p')
				->select('p')
				->where('p.level <= :player_lvl')
				->addOrderBy('p.level','DESC')
				->setParameter('player_lvl', $level);
		
		if (false === is_null($limit))
       	 		$qb->setMaxResults($limit);
		
    		return $qb->getQuery()
              		->getResult();		
		
	} 
	
	
		
}
